kind: pipeline
name: token
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: token:dev
    image: docker:dind
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
        
    commands:
      - docker build -f ./src/CloudStorage.HttpApi.Host/Dockerfile -t registry.cn-shenzhen.aliyuncs.com/tokengo/cloud-storage:dev .
      - docker stop cloud-storage && docker rm  cloud-storage
      - docker run -d -e ASPNETCORE_ENVIRONMENT=Development --network token --name cloud-storage registry.cn-shenzhen.aliyuncs.com/tokengo/cloud-storage:dev

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
      
---
kind: pipeline
name: 收尾
type: docker

steps:
  - name: 清楚镜像
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker system prune -f

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
      
depends_on:
   - token