kind: pipeline
name: token
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: token:dev
    when:
      branch:
        - master
    image: docker:dind
    environment:
      IMAGE: token:dev
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f ./src/token.Web/Dockerfile  -t token:dev .
      
  - name: token-push
    image: docker:dind
    when:
      branch:
        - master
    environment:
      IMAGE: token:dev
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: logs
        path: /root/logs/token/logs:/app/logs
    commands:
      - docker stop token && docker rm token
      - docker run -d -p 8000:80 -p 8081:443 -v /root/logs/token/logs:/app/log --network token -e ServiceName=token -e ServicePort=80 -e ASPNETCORE_ENVIRONMENT=Development --restart always --name token token:dev

  - name: token-push1
    image: docker:dind
    when:
      branch:
        - master
    environment:
      IMAGE: token:dev
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: logs
        path: /root/logs/token1/logs:/app/logs
    commands:
      - docker stop token1 && docker rm token1
      - docker run -d -v /root/logs/token1/logs:/app/log --network token  -e ServiceName=token1 -e ServicePort=80 -e ASPNETCORE_ENVIRONMENT=Development --restart always --name token1 token:dev

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: signalr
type: docker

platform:
  os: linux
  arch: amd64
  
steps:
  - name: signalr:dev
    when:
      branch:
        - master
    image: docker:dind
    environment:
      IMAGE: signalr:dev
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f ./src/SignalR/token.SignalR.Web/Dockerfile  -t signalr:dev .

  - name: signalr-push
    image: docker:dind
    when:
      branch:
        - master
    environment:
      IMAGE: signalr:dev
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: logs
        path: /root/logs/signalr/logs:/app/logs
    commands:
      - docker stop signalr && docker rm signalr
      - docker run -d --network token -e ASPNETCORE_ENVIRONMENT=Development -v /root/logs/signalr/logs:/app/logs  --restart always --name signalr signalr:dev

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: after
type: docker

steps:
  - name: notify
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker system prune -f
      
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
depends_on:
  - token
  - signalr