kind: pipeline
name: token
type: docker

platform:
  os: linux
  arch: amd64
  
steps:
  - name: token:dev
    image: docker:dind
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
      TOKEN:
        from_secret: token-k3s
      SIGNALR:
        from_secret: signalr-k3s
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f ./src/token.Web/Dockerfile -t registry.cn-shenzhen.aliyuncs.com/tokengo/token:dev .
      - docker build -f ./src/SignalR/token.SignalR.Web/Dockerfile -t registry.cn-shenzhen.aliyuncs.com/tokengo/token-signalr:dev .
      - docker login --username=$USERNAME registry.cn-shenzhen.aliyuncs.com --password=$PASSWORD
      - docker push registry.cn-shenzhen.aliyuncs.com/tokengo/token:dev
      - docker push registry.cn-shenzhen.aliyuncs.com/tokengo/token-signalr:dev

  - name: k3s
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/ubuntu
    environment:
      TOKEN:
        from_secret: token-k3s
      SIGNALR:
        from_secret: signalr-k3s
    commands:
      - $TOKEN
      - $SIGNALR
    
    
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: after
type: docker

steps:
  - name: notify
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker system prune -f
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
      
depends_on:
   - token