kind: pipeline
name: token
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: token:dev
    image: docker:dind
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
        
    commands:
      - docker build -f ./src/CloudStorage.HttpApi.Host/Dockerfile -t registry.cn-shenzhen.aliyuncs.com/tokengo/cloud-storage:dev .
      - docker login --username=$USERNAME registry.cn-shenzhen.aliyuncs.com --password=$PASSWORD
      - docker push registry.cn-shenzhen.aliyuncs.com/tokengo/cloud-storage:dev
 
  - name: token部署到k3s
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/ubuntu
    commands:
      - "curl -X PUT -H \"Content-Type: application/yaml\" -H \"Cookie: KuboardUsername=admin; KuboardAccessKey=izbryrexyfet.cf2bzi27mstj6s3eh5x52n6xyinxyeny\" -d '{\"kind\":\"deployments\",\"namespace\":\"default\",\"name\":\"cloud-storage\"}' \"http://124.222.27.83:30080/kuboard-api/cluster/default/kind/CICDApi/admin/resource/restartWorkload\""

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
      
---
kind: pipeline
name: 收尾
type: docker

steps:
  - name: 清楚镜像
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker system prune -f

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
      
depends_on:
   - token