kind: pipeline
name: token
type: docker

platform:
  os: linux
  arch: amd64
  
steps:
  - name: token:dev
    image: docker:dind
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f ./src/token.Web/Dockerfile -t registry.cn-shenzhen.aliyuncs.com/tokengo/token:dev .
      - docker login --username=$USERNAME registry.cn-shenzhen.aliyuncs.com --password=$PASSWORD
      - docker push registry.cn-shenzhen.aliyuncs.com/tokengo/token:dev

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: signalr
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: signalr:dev
    image: docker:dind
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f ./src/SignalR/token.SignalR.Web/Dockerfile -t registry.cn-shenzhen.aliyuncs.com/tokengo/token-signalr:dev .
      - docker login --username=$USERNAME registry.cn-shenzhen.aliyuncs.com --password=$PASSWORD
      - docker push registry.cn-shenzhen.aliyuncs.com/tokengo/token-signalr:dev
      - curl -X PUT -H "content-type: application/json" -H "Cookie: KuboardUsername=admin; KuboardAccessKey=izbryrexyfet.cf2bzi27mstj6s3eh5x52n6xyinxyeny" -d '{"kind":"deployments","namespace":"default","name":"web-sginalr","images":{"registry.cn-shenzhen.aliyuncs.com/tokengo/token-signalr":"registry.cn-shenzhen.aliyuncs.com/tokengo/token-signalr:dev"}}' "http://124.222.27.83:30080/kuboard-api/cluster/default/kind/CICDApi/admin/resource/updateImageTag"
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: after
type: docker

steps:
  - name: notify
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker system prune -f
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
      
depends_on:
   - token
   - signalr